services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=sys_files
      - DB_PORT=5432
    volumes:
      - .:/file-service
    restart: unless-stopped

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sys_files
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: